---
        - name: "To remove temp zip files from source host at begining of the play"
          file:
            path: /tmp/{{ ansible_hostname }}_dsmerror_logs.zip
            state: absent

        - name: "To list the dsmerror log file on soruce hosts"
          find:
#            paths: /opt/tivoli/tsm/client/ba/bin
            paths: "{{ dsmerrorlog_path }}"
            patterns: "dsmerror*"
            recurse: no
          register: dsmerrorlogfiles

        - debug:
            msg: "{{ dsmerrorlogfiles.files | map(attribute='path') | list }}"  

        - name: "Create a zip file of dsmerror log files"
          archive:
            path: "{{ dsmerrorlogfiles.files | map(attribute='path') | list }}"
            dest: "/tmp/{{ ansible_hostname }}_dsmerror_logs.zip"
            format: zip